version: "3"
services:
    nginx: 
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        depends_on:
          - api 
          - client
    client:
        image: colgworld/kubetest-client
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client/src/
        entrypoint: ["npm", "start"]
        links:
            - api
    api:
        image: colgworld/kubetest-api
        restart: always
        ports:
            - "9000:9000"